import { AxiosResponse } from 'axios'
import { GetServerSidePropsContext } from 'next'
import Head from 'next/head'
import React from 'react'
import Tabs from '../../components/Tabs'
import { fetchArticles, fetchCategories } from '../../http'
import { IArticle, ICategory, ICollectionResponse, IPagination } from '../../types'
import qs from 'qs'
import ArticleList from '../../components/ArticleList'
import Pagination from '../../components/Pagination'
import { makeCategory } from '../../utils'
import { useRouter } from 'next/router'

interface IPropTypes {
    categories: {
        items: ICategory[],
        pagination: IPagination
    },
    articles: {
        items: IArticle[],
        pagination: string
    },
    slug: string
}


export default function Category({ categories, articles, slug }: IPropTypes) {
    const { page, pageCount } = articles.pagination
    const router = useRouter();
    const { category: categorySlug } = router.query;

    const formatedCategory = (slug: string) => {
        return makeCategory(slug)
    }

    return (
        <>
            <Head>
                <title>My Blog {formatedCategory(slug)}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Tabs 
                categories={categories.items} 
            />
            <ArticleList 
                articles={articles.items} 
            />
            <Pagination 
                page={page} 
                pageCount={pageCount} 
                redirectUrl={`/category/${categorySlug}`} 
            />
        </>
    )
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
    const options = {
        populate: ['author.avatar'],
        sort: ['id:desc'],
        filters: {
            Category: {
                slug: context.query.category,
            },
        },
        pagination: {
            page: context.query.page ? context.query.page : 1,
            pageSize: 1
        }
    }

    const queryString = qs.stringify(options)

    const { data: articles }: AxiosResponse<ICollectionResponse<IArticle[]>> = await fetchArticles(queryString)

    const { data: categories }: AxiosResponse<ICollectionResponse<ICategory[]>> = await fetchCategories()

    return {
        props: {
            categories: {
                items: categories.data
            },
            articles: {
                items: articles.data,
                pagination: articles.meta.pagination
            },
            slug: context.query.category
        }
    }
}